### ISSUE TITLE
Status of Packet Loss Concealment (PLC)

### ISSUE THREAD

**Issue by mringwal** [google/liblc3#16]
Thanks for providing this excellent and fast LC3 Codec as an open source project.

I'd like to ask about the status of the Packet Loss Concealment. 

When I run a simple test encoding a sine wave and dropping every 20th packet, it clearly becomes audible. The test is here: https://github.com/bluekitchen/liblc3/tree/plc-test/plc-test (regular CMake project, should build with no other dependencies).

The LC3 specifications defines a minimal PLC in Appendix B. Is that implemented (and just not good enough), or would this help?

For SBC, it was possible to replace a dropped packet with a fixed 'zero frame', which worked well at least for the simple case with a periodic dropped packet.

Thanks
 Matthias

**Comment by asoulier** [comment]
Thanks for your interest.

Yes, the implemented PLC is the one specified in Appendix B of the standard. It replicates the spectrum coefficients of the last good frame and scrambles the sign of the coefficients on each iteration. On a pure sine signal, it will reproduce a signal at the same level and same frequency, but the phase will be broken at each frame boundary. Sure, it will be audible on such a signal.
From my hearing tests, that doesn't sound too bad on voiced signals (call usage). On music content, I think it's much more limited.

I have done some quick studies using the pitch value computed by the encoder. In this way, we can easily continue the fundamental frequency in the temporal domain. That will greatly patch the hole in the pure sine signal, and I found that it sounds much better on music signals.
This approach certainly needs more subjective hearing tests.

Moreover, If you prefer to patch with "zero frame" or silence, you can easily do that by checking the return value of `lc3_decode()`. When PLC operates, you can `memset()` to 0 the returned samples. But I think the PLC will do a slightly better job.

Have you tried to listen with different types of real signal?

**Comment by mringwal** [comment]
Hi. Thanks for the explanations. It's great to learn that the codec fulfills the specification!

As a quick test of my understanding, I've disabled the "sign scrambling of the coefficients" in plc.c and got a perfect sine wave back with the test code. This is the same behaviour as in SBC.

The "Zero frame" I was referring is [this](https://github.com/bluekitchen/btstack/blob/master/src/classic/btstack_sbc_plc.c#L60). As far as I understand, it contains an SBC frame with 'don't change the spectrum' information.

I haven't tried testing packet loss with real voice or audio signals, but we will do in the next time. I guess the main use will be missing packets in broadcast audio as for personal audio with unicast, most packets should be delivered correctly.

You can close the issue unless it might provide information for others, too,

Cheers
 Matthias
