### ISSUE TITLE
Introduce LC3_PCM_FORMAT_FLOAT

### ISSUE THREAD

**Issue by Vudentz** [google/liblc3#2]
Looks like the internal processing is using floating point with the existing formats (s16,s24) just converting to it so perhaps it would be a good idea to introduce the floating point at API level in case the audio server is already using floating point then it doesn't have to convert to fixed point just to call liblc3 APIs.

**Comment by asoulier** [comment]
Yes you're right. The question has arisen, when the 24 bits has been introduced.
I just have to do a quick review with that, as floating points are commonly used in normalized range -1 to 1 for audio samples.
All internal processing is currently done on floating point but in range of 16 bits integer (-32768 to 32767).
If you need this, can be introduced with a conversion step, before working internally on normalized range.

**Comment by asoulier** [comment]
done.
