### ISSUE TITLE
lc3_decode: Query on leading and trailing extra samples in the decoded output

### ISSUE THREAD

**Issue by tkanakamalla** [google/liblc3#29]
The pcm output of the decoder seems to have some leading and trailing extra samples? Why is the decoder producing those additional bytes?

From the `dlc3.c` code, I see it strips off those bytes before writing them to wav file. So apparently those are unwanted.

https://github.com/google/liblc3/blob/3d769309ffacb3c18b4a0bdd6b46544eb26bbfb2/tools/dlc3.c#L234-L236

**Comment by asoulier** [comment]
It is an MDCT-based codec. The frequency domain transformation of discrete time frames involves windowing (overlap between frames). The encoder must show `lc3_delay_samples()` to perform the overlap and produce a complete frame. The future is initialized to `0` on the encoder side. For the decoder, this shift becomes past to be shown; it's also initialized to `0`.

From the user, you'll need to keep in mind that the codec inducts algorithmic delay of `lc3_delay_samples()`. This delay is removed for file-based compression to stay aligned with the source. When a stream is decoded, the first `lc3_delay_samples()` will shape as a steep fade-in, almost a great side effect.

Regarding the extra number of output samples, the codec process only frames 7.5 ms or 10 ms in length. The duration of the source file is probably not a multiple of this frame size (plus delay). To encode the remaining samples, the final frame is completed with `0` at the encoder side. The number of samples of the original source file is stored in the header as `nsamples`. The decoder discards those samples to write a file with the same duration.

For the first frame (`i == 0`), `pcm_offset` is set to `lc3_delay_samples()`, we discard the delay.
The extra samples at the end are discarded by `encode_samples - i*frame_samples`. `encoded_samples` is the number of source samples + delay. And we align to a discrete number of frames.
