### ISSUE TITLE
Integrate with google/oss-fuzz for continuous fuzz-testing

### ISSUE THREAD

**Issue by silvergasp** [google/liblc3#31]
Hey I'd like to suggest adding liblc3 to google/oss-fuzz. If you aren't familiar with fuzz testing, here is a bit of a run down ([from Wikipedia](https://en.wikipedia.org/wiki/Fuzzing));

> In [programming](https://en.wikipedia.org/wiki/Computer_programming) and [software development](https://en.wikipedia.org/wiki/Software_development), fuzzing or fuzz testing is an automated [software testing](https://en.wikipedia.org/wiki/Software_testing) technique that involves providing invalid, unexpected, or [random data](https://en.wikipedia.org/wiki/Random_data) as inputs to a [computer program](https://en.wikipedia.org/wiki/Computer_program). The program is then monitored for exceptions such as [crashes](https://en.wikipedia.org/wiki/Crash_(computing)), failing built-in code [assertions](https://en.wikipedia.org/wiki/Assertion_(software_development)), or potential [memory leaks](https://en.wikipedia.org/wiki/Memory_leak).

Fuzz tests differ a little to the unit/integration tests already in the liblc3 repository as the fuzzer will attempt to generate malformed inputs that may trigger those otherwise hard to find edge-cases or bugs that wouldn't be capture using regular testing.

If liblc3 is integrated into oss-fuzz, the fuzz tests under liblc3 will be built and then run once a day, to search for bugs and vulnerabilities in liblc3. This service can be integrated with the CI for liblc3, so that the fuzz tests are run for 10min or so for every pull request, preventing buggy code from being merged.

I've opened up a pull request to add a basic fuzz-testing harness here #30 just to demonstrate what this would look like. If you are keen on adding liblc3 to oss-fuzz I'd be happy to champion the integration :)

**Comment by silvergasp** [comment]
Easy, what I'll do is focus on getting things integrated into oss-fuzz and then I can use the [oss-fuzz CI github action](https://google.github.io/oss-fuzz/getting-started/continuous-integration/). So the way this will work is as follows;
- oss-fuzz will build/fuzz the code once a day every day (for X hours)
- The github action will build/fuzz the code on every PR for 10min or so (we can customize this). This CI implementation will hopefully catch shallow bugs before they are merged, but it'll also prevent any bitrot in the fuzzers.

**Comment by asoulier** [comment]
Looks good!
Thanks!
