### ISSUE TITLE
LC3 encode  0db sweep sine signal and decode bitstream, the  output sine signal is clipped;

### ISSUE THREAD

**Issue by WenzhengQ** [google/liblc3#33]
1.encode the wav
./elc3 -b 128000 -m 10 48khz_16bit_2ch.wav  48khz_16bit_2ch_enc_kbps.bin
2.decode the bitstream
./dlc3 48khz_16bit_2ch_enc_kbps.bin 48khz_16bit_2ch_enc_kbps_dec.wav

**Comment by asoulier** [comment]
Thanks for your comment.

Yes, it's a known artifact of the "Long-Term Post Filter" (LTPF), that adds gain on pure sine signals.
It's a specificity of this parametric tools. The gain will be less with higher sinus frequency, and will be maximum around 1 dB (volume under 90% will be OK).

This issue has already been mentioned (here)[https://github.com/zephyrproject-rtos/liblc3codec/issues/9]

At higher bitrate, the LTPF is disabled; you'll don't encounter this artifact.

**Comment by WenzhengQ** [comment]
@asoulier  
Thanks for your reply.
I disable ltpf unconditionally  in analyse() function of the lc3.c file; output sine signal is normal; 

//    if (nn_flag)
        lc3_ltpf_disable(&side->ltpf);

But I set encode bitrate=500kbps, encode the same full scale sweep sine(20hz-24khz)  and decode the bitstream;  the ouput sine signal has more harmonic at higher sinus frequency; when i set encode bitrate=128kbps, output sine has less harmonic  than bitrate=500kbps;

1.encode the wav
./elc3 -b 500000 -m 10 48khz_16bit_2ch.wav 48khz_16bit_2ch_enc_500kbps.bin
2.decode the bitstream
./dlc3 48khz_16bit_2ch_enc_500kbps.bin 48khz_16bit_2ch_enc_500kbps_dec.wav

**Comment by asoulier** [comment]
Thank for these observations.

Note that the bandwidth is limited to 20 KHz.   
I have generated a mono linear sweep 20 Hz to 20 KHz.
And done the encoding/decoding loop :
```
./bin/elc3 /tmp/sweep.wav -b 64000 | ./bin/dlc3 > /tmp/sweep_64k.wav
./bin/elc3 /tmp/sweep.wav -b 128000 | ./bin/dlc3 > /tmp/sweep_128k.wav
./bin/elc3 /tmp/sweep.wav -b 256000 | ./bin/dlc3 > /tmp/sweep_256k.wav
```
![image](https://github.com/google/liblc3/assets/103120622/c6602003-3072-498c-9e11-a9e7a2c755ad)

The first track is the linear spectrogram of source sweep, next it's 64k, 128k and 256k ones.

It seems you're completely right. I will look in following days.
Thanks.

**Comment by asoulier** [comment]
Discussion moved into https://github.com/google/liblc3/issues/34
