### ISSUE TITLE
Volume adjustment

### ISSUE THREAD

**Issue by sam131208** [google/liblc3#36]
Is it possible to support volume adjustment when decoding like OPUS, so that some cases without external volume adjustment can be adjusted by software?

```c
 if(st->decode_gain)
   {
      opus_val32 gain;
      gain = celt_exp2(MULT16_16_P15(QCONST16(6.48814081e-4f, 25), st->decode_gain));
      for (i=0;i< (frame_size/st->downsample)*st->channels;i++)
      {
         opus_val32 x;
         x = MULT16_32_P16(pcm[i],gain);
         pcm[i] = SATURATE(x, 32767);
      }
   }
```

**Comment by asoulier** [comment]
Thanks for your proposition.

The volume steps (or volume curve) are typically linear in dB (following human ears sensitivity), so you'll have to convert you're volume value in a magnitude, with `10^(n/20)`, `n` being in range `-60..0`, for attenuation between -60dB to 0dB. Opus is doing something similar, using the power of 2, but it remains a slightly different interpretation. I am not convinced that this conversion must be more codec-specific than system-specific.

Moreover, you should avoid a dynamic steep change of gain; you introduce discontinuity on the signal. As I know, hardware handles volume change on signal zero-cross. When operated in software, adding a low-pass filter (fading) on step change is often easier and more efficient. You'll hear some "scratches" on changes without correct transition handling.

For those reason, I think this is not the right place for handling volume change.
It can be better handled, and customized, after the decoding.
