### ISSUE TITLE
[feature request] manipulate mono channel enc/dec from tool

### ISSUE THREAD

**Issue by rick1082** [google/liblc3#39]
Thanks for the great liblc3! Pardon me to raise a feature request in here. Since I found the elc3 from tool cannot handle the mono channel WAV file, would it possible to extend the the tool for handling the mono channel audio ? that would be wonderful! Many thanks!

**Comment by asoulier** [comment]
Hi,
It should be supported.
Do you have any errors? Can you share a sample file?
Note that 44.1 KHz samplerate is not supported.

**Comment by rick1082** [comment]
Pardon me for the late reply, please let me share the sample file and also the detail in here:

1. There's a test .wav file "stereo.wav" which is stereo (from https://www.youtube.com/watch?v=wVrC-XQ9Crg). 
2. Use ffmpeg to convert it from stereo to mono with the following command: $ ffmpeg -i stereo.wav -ac 1 mono.wav
3. Use elc3 for encoding the mono.wav: $./elc3 -b 80000 -m 10 -r 48000 mono.wav mono.bin
4. The error message shows "Bad or unsupported WAVE input file: Invalid argument"

Please let me attach both stereo.wav and mono.wav in the below:
[wav_samples.zip](https://github.com/google/liblc3/files/13291854/wav_samples.zip)

**Comment by asoulier** [comment]
Thanks for the detailed steps.
It will be fixed, the WAV files contains some sort of metadatas (there is a LIST chunk), it's now skipped.
