### ISSUE TITLE
Query - can we change build based on GNU autotools or meson system ?

### ISSUE THREAD

**Issue by kirankrishnappa-intel** [google/liblc3#4]
@asoulier - We are using this LC3 codec in PulseAudio and wanted to have either GNU autools based or meson based build. Will that be compatible with android build ?  If not, then I can add "install" target to the exisiting native makefile. Thanks.

**Comment by asoulier** [comment]
@kirankrishnappa-intel I don't see any compatibility with android build (using basel).
There is no problem to add another build system, as long as that t the make is not broken (used for embedded projects).
But before I can accept any pull requests, you have to sign a CLA (https://cla.developers.google.com/clas).

For install target, can you have a look to https://github.com/google/liblc3/compare/main...install-target
If that works for you, I can merge it.

**Comment by kirankrishnappa-intel** [comment]
> But before I can accept any pull requests, you have to sign a CLA (https://cla.developers.google.com/clas).
@asoulier  - I am already covered under the name - "Intel CLA Submissions". Thanks.

**Comment by asoulier** [comment]
Oh fine, so no problem that you add meson based build or patchs ;)
