### ISSUE TITLE
Add options to parse a lc3 bitstream without the custom header in dlc3

### ISSUE THREAD

**Issue by DeltaEvo** [google/liblc3#43]
It would be nice to be able to parse a raw lc3 bitstream with dlc3 by providing the frame_us, srate_hz, hrmode, nchannels, nsamples and the block bytes directly on the command line.

**Comment by asoulier** [comment]
I think this will add two much complexity to the tools usage.
You can try the [decoder.py](https://github.com/google/liblc3/blob/libpython/python/tools/decoder.py) and [encoder.py](https://github.com/google/liblc3/blob/libpython/python/tools/encoder.py) using the python wrapper, to easily customize the I/O. This will be merged soon.
I will add documentation on the binary header, it's not a custom header, it's defined in the testing docs.
(LC3 - TS 3.2.8.2)[https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=502301].
