### ISSUE TITLE
Conformance test problem

### ISSUE THREAD

**Issue by chrisycw03** [google/liblc3#47]
I did the conformance test by [Test Software v1.0.6](https://www.bluetooth.com/specifications/specs/low-complexity-communication-codec-1-0/). However, the encode and encode-decode report with 7.5ms frame were failed. I found out the ODG of LC3 is much larger than the reference ODG that cause the delta ODG exceed the threshold(0.06). I guess it is due to the PEAQ algorithm. Could you let me know which PEAQ did you implement?

**Comment by asoulier** [comment]
Yes, I think the problem actually comes from the PEAQ algorithm. I encountered the same issue ;).
It's specified in [LC3 - Test Suite](https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=502301), that a PEAQ **Advandced** implementation is needed (3.2.4).
I never found a PEAQ **Advanced** open-source implementation.
I actually rely on [Opticom tool](https://www.opticom.de/technology/peaq.php)
Note that it doesn't support 96 KHz and 24 bits (not suitable for LC3+ HR).
But I can confirm that Fraunhofer has crossed-checked the results, using the ODG metric (PEAQ) on LC3+ HR.
