### ISSUE TITLE
LC3_EXPORT macro breaks compilation with MSVC

### ISSUE THREAD

**Issue by amyspark** [google/liblc3#48]
Hi,

This is to report that on #44 a `LC3_EXPORT` macro was added to aid in managing the ABI of liblc3. However, using this macro prevents compiling the library at all on MSVC, it needs to be changed to `__declspec(dllexport)` in that case.

Fixing this issue will also enable building shared libraries without further change under MSVC -- previous to that PR, the shared library had an empty ABI and so had no import library generated at link time.

**Comment by asoulier** [comment]
Hi,

Thanks for reporting this.
I am unable to test with MSVC, sorry for that. Can you check that https://github.com/google/liblc3/pull/49 works?

Thanks.
