### ISSUE TITLE
FFmpeg liblc3 build failure

### ISSUE THREAD

**Issue by Andarwinux** [google/liblc3#55]
Although this is not a problem with liblc3 itself, since FFmpeg's trac is very difficult to use, and since you are a liblc3 maintainer, I would like to report this problem here.

https://github.com/FFmpeg/FFmpeg/commit/45d2110fc72638c47a60b35511b4367fa65583cc seems to have introduced a typo: DECODER_MAX_CHANNES, which was supposed to be DECODER_MAX_ CHANNELS?

**Comment by asoulier** [comment]
Yes I saw it yesterday, a [patch](https://patchwork.ffmpeg.org/project/ffmpeg/patch/20240404225734.3036715-1-asoulier@google.com/) is in the pipe, but the review takes time.
