### ISSUE TITLE
Warning of INFINITY used in -ffast-math mode

### ISSUE THREAD

**Issue by yabinc** [google/liblc3#58]
Hi,

-Wnan-infinity-disabled is a new warning added recently in clang, in https://github.com/llvm/llvm-project/pull/76873.
It finds the following place using INFINITY in arithmetic operations in fast-math mode.
Please help check if it worth fixing.

external/liblc3/src/sns.c:550:21: error: use of infinity via a macro is undefined behavior due to the currently enabled floating-point options [-Werror,-Wnan-infinity-disabled]
  550 |     float mse_min = INFINITY;
      |                     ^
external/liblc3/src/sns.c:555:26: error: use of infinity via a macro is undefined behavior due to the currently enabled floating-point options [-Werror,-Wnan-infinity-disabled]
  555 |         float cmse_min = INFINITY;
      |                          ^

**Comment by asoulier** [comment]
Hi,

Thanks for the catch, INFINTY removed with #59.
