### ISSUE TITLE
Floating Point Exception in tools/wave.c:117

### ISSUE THREAD

**Issue by vanhauser-thc** [google/liblc3#9]
I found a FPE in tools/wave.c:117:
```
int wave_read_header(FILE *fp, int *bitdepth, int *samplesize,
    int *samplerate, int *nchannels, int *nframes)
{
    ...
    *samplesize = format.framesize / format.channels;
    ...
```
No validation of the input is performed so format.channels can be 0.
I attached an example wav.
[example.zip](https://github.com/google/liblc3/files/9475411/example.zip)

**Comment by asoulier** [comment]
Thanks for pointing this. I just added some more checks on wave inputs.
